### ISSUE TITLE
Generate higher resolution HDR

### ISSUE THREAD

**Issue by chris-hndz** [DiffusionLight/DiffusionLight#2]
I congratulate you for your excellent project and for the amazing results of your work!

I wanted to ask you, what part of the code would you recommend to modify to get higher resolution HDR (512 x 512, 1024 x 1024, 2048 x 2048) (even if this significantly increases the processing time) ?

Thank you very much in advance!

**Comment by pureexe** [comment]
I don't recommend increasing the resolution because the SDXL is trained on 1024x1024 images, and we inpaint the ball of size 256x256 into the middle of the image. Increasing the resolution might not produce a plausible output.

However, if you want to increase the size of the HDR environment map, I would recommend increasing both the size of the ball and the size of the input image simultaneously. This is because our LoRA is only trained to handle the case of a single ball size in the middle of the image.

For example, if you want a ball size of 512 instead of 256, here are the commands to run:


```
python inpaint.py --dataset example --output_dir output/higher2048 --img_height 2048 --img_width 2048 --ball_size 512 --algorithm normal 
python ball2envmap.py --ball_dir output/higher2048/square --envmap_dir output/higher2048/envmap --envmap_height 512
python exposure2hdr.py --input_dir output/higher2048/envmap --output_dir output/higher2048/hdr
```

**Comment by chris-hndz** [comment]
ok, thank you for your reply!
